### ISSUE TITLE
Question about constant 50 in update_z function in TransCLIP_utils.py

### ISSUE THREAD

**Issue by Yingping-LI** [MaxZanella/transduction-for-vlms#1]
Hello Maxime and Benoît,

Thank you for this amazing work!

I have a question regarding the code:
- In the update_z function within the file TransCLIP_solver/TransCLIP_utils.py, I noticed that a constant value of 50 is used. Could you please help clarify the reasoning behind using this constant and how it was chosen?
Thanks in advance for your help!

Best regards,
Yingping

**Comment by MaxZanella** [comment]
Hi Yingping,

Apologies for the delayed response. This constant originates from weighting the entropy in the original objective function. Specifically, highest entropy regularization encourages uniform class predictions, which manifests as a temperature scaling factor in the softmax operation of the z-update after derivation. In our experiments, this value is kept fixed across all tasks. However, tuning it for a specific task might certainly lead to improved performance.
Let me know if you have further questions or need additional details!

**Comment by Yingping-LI** [comment]
Hello Maxime,

Thanks a lot for your detailed and clear explanation. It is very helpful!
Have a nice day : )

Best,
